### ISSUE TITLE
Scope tool architecture around user interfaces and APIs

### ISSUE THREAD

**Issue by amedina** [GoogleChromeLabs/ps-analysis-tool#11]
## Task

**Description:**
Ad described in the Readme, this tool targets a specific [target audience](https://github.com/GoogleChromeLabs/ps-analysis-tool#target-audience), and therefore provides capabilities that serve different use cases. The tool has modules connected to the following user interfaces:

1. DevTools Panel
2. Icon, Icon Popup, and Side Panel
3. Google Admin Console

The tool architecture allows this modules to be decoupled, allowing each of this user interfaces to be delivered independently later. 

**Steps to Complete:**
- [x] System's level overview
- [ ] Detailed module specifications
- [ ] Input and output for all components
- [ ] Information handling flows during browsing sessions
- [ ] Update README file

**Comment by amedina** [comment]
#12 and #47 are related to this task.
