### ISSUE TITLE
Epic: Implement Chrome DevTools Protocol in Data Layer.

### ISSUE THREAD

**Issue by amovar18** [GoogleChromeLabs/ps-analysis-tool#247]
## Feature Request
Implement Chrome DevTools Protocol in the data layer to get the missing data which we don't get from the current APIs.

**Acceptance Criteria:**
- [x] #248
- [x] #249
- [x] #250
- [x] #251
- [x] #253
- [x] #252
- [x] #254
- [x] https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/241
- [x] https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/268
- [x] https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/245
- [x] https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/242
- [x] https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/240
- [x] https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/259

**Additional Information:**
Progress regarding Chrome DevTools Protocol research was made in https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/156

**Comment by amovar18** [comment]
For more detailed technical implementation for this issue, you can check the PR description.

**Comment by maitreyie-chavan** [comment]
Released as a part of [v0.4.0](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.4.0), closing this issue.
