### ISSUE TITLE
Rendering of cookies for frames in Cookies Table is being delayed

### ISSUE THREAD

**Issue by amedina** [GoogleChromeLabs/ps-analysis-tool#380]
**Describe the bug**
When using the Privacy Sandbox Analysis Tool Extension (PSAT) on Chrome, the Privacy Sandbox panel correctly displays information about the cookies on the cookies landing page. However, when clicking on any of the frames, the tables are empty, and the cookie details do not appear for an extended and random period. The delay varies greatly, sometimes being as short as 5-10 seconds and other times taking minutes.

**To Reproduce**
1. Open Chrome and navigate to a site with the Privacy Sandbox Analysis Tool Extension (PSAT) enabled.
2. Click on the Privacy Sandbox panel to view the cookies landing page.
3. Observe the blocking information displayed in the Cookies Landing page
4. Click on the top frame and observe table populated with cookies for that frame
5. Click on any of the frames, and notice the empty tables and the delayed display of cookie information.
6. Wait for some period of time, and see the cookie information being displayed

**Expected behavior**
When clicking on any of the frames within the Privacy Sandbox panel, the cookie details should load promptly and display the relevant information without significant or random delays.

**Tasks**
- [x] https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/403
- [x] https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/404
- [x] https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/405

**Comment by maitreyie-chavan** [comment]
Addressed and released as a part of [v0.5](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.5.0)
