### ISSUE TITLE
[Epic] Uniform Filtering developer experience across frames

### ISSUE THREAD

**Issue by maitreyie-chavan** [GoogleChromeLabs/ps-analysis-tool#396]
### Description:

Refine the PSAT extension's filtering capabilities to support the persistence of filter settings across multiple frames. This enhancement should enable users to uniformly apply most filters throughout all frames, at the same time, dynamically adapting to available data for certain filters. It will include comprehensive blocking reasons and custom handling for domain-based filtering, aiming to provide a more efficient filtering experience.

### Motivation:

Currently, the PSAT extension's filter settings are limited to individual frames, which slows down the analysis process across multiple frames. By enhancing this feature, developers and analysts will be able to conduct faster, more coherent analyses across multiple frames, significantly accelerating the audit process and improving overall productivity.

### User Story:

As a developer I want to seamlessly filter and analyze data across multiple frames in an uniform and consistent way. PSAT filtering capabilities should enable me to smoothly navigate between multiple filtered frames without the repetitive task of reapplying filters for each one, thereby optimizing my workflow and boosting efficiency.

### Acceptance Criteria:

- [x]  Implement **static persistent filters** that maintain their settings consistently across multiple frames.
- [x]  Implement **dynamic persistent filters** that consolidate all values from all frames into a unified filter menu.
- [x]  Implement **dynamic non-persistent filters** that adapt based on the data available in each frame , enhancing real-time analysis flexibility.
- [x]  Ensure that **persistent filters** remain stable and unchanged when users switch between frames, ensuring a continuous analytical flow.
- [x]  Maintain the filter section's visibility, when switching to different frames, even when the resultant data set is empty, to avoid disrupting the user's analytical process.

### Proposed categorization of filters

**Static Persistent Filters:**

1. Scope
2. HttpOnly
3. SameSite
4. Secure
5. Retention Period
6. Set Via
7. Priority
8. Blocked

**Dynamic Persistent Filters:**

1. Category (dynamic)
2. Platform
3. Blocked Reasons

**Non-Persistent Filters:**

1. Domain
2. Path

**Sub-task**

- [x] https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/371
- [x] https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/255
- [x] https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/332
- [x] https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/374

**Comment by kjnanda** [comment]
@mayan-000 Please check the below issues.

- [ ] Filter icon should not be enabled for empty table.

**Comment by kjnanda** [comment]
### Filter icon should not be enabled for empty table.

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/ad1e7be4-77fe-44a5-b947-7ce8597535e8

**Comment by maitreyie-chavan** [comment]
Addressed and released as a part of [v0.5](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.5.0)
