### ISSUE TITLE
[QA] CDP Switch 

### ISSUE THREAD

**Issue by kjnanda** [GoogleChromeLabs/ps-analysis-tool#410]
## Scenarios verified for CDP Switch

| Scenario | Status | 
| --- | --- | 
| By default, Use CDP switch will be disabled | ✅ |
| After installing the extension and opening a new URL, observe two things here:<li>Ensure that the 'Use CDP' switch is off<br/><li>Confirm that the debugger notice is not visible | ✅ |
| Turning on CDP: <li>Debugger notice should appear (may take a moment) <br/><li>No errors should occur on the chrome://extension page.<br/><li>Page will be auto-refreshed for accurate information.<br/><li>Blocked cookies should be highlighted in yellow.<br/><li>Blocked reason should be visible when user clicks on blocked cookie. | ✅ |
| Turning off the CDP:<li>The debugger notice should disappear; please allow some time for this change.<br/><li>No errors should occur on the chrome://extension page.<br/><li>Page will be auto-refreshed to obtain the correct information.<br/><li>Blocked cookies should no longer be highlighted in yellow. | ✅ |
| Clicking on "Analyse this tab" button from the popup and cookies landing page should not throw any errors. | ✅ |
| Blocked cookie count should not have discrepancies in a single tab and multi-tab. | ✅ |
| Switching on/off from a different tab should effectively work on the current tab being analysed. | ✅  |
| Cancelling the debug bar and turning off the CDP switch should result in refreshing the page and fetching the correct result. | ✅  |

----

- [x] [Issue with CDP Switch Handling: Debugger Notification, Blocked Cookie Count, and Sidebar Display ](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/410#issuecomment-1884916267) 
- [x] [Suggestion to add tooltip](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/410#issuecomment-1884918897)
- [x] [Page is not refreshed after canceling Debug Bar with CDP Switch OFF](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/410#issuecomment-1886251156) 
- [x] [Inconsistent behavior when testing CDP Switch in Multi-Tab environment](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/410#issuecomment-1886375960) 
- [x] [Unexpected cookie count issue after the switch is on/off](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/410#issuecomment-1886450521)
 ~[Issue while switching from Multi-Tab to Single Tab](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/410#issuecomment-1886733632)~ **Not in scope**
- [x] [Evaluating the need for additional labels in Popup for CDP Switch](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/410#issuecomment-1886751594)
- [x] [Issue with Cookie count: Delayed Loading or Incorrect Values in multi tab environment](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/410#issuecomment-1886807485) 🤔 
- [x] [There is a noticeable jumping effect while toggling the setting from DevTools](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/410#issuecomment-1893520477)
- [x] [Enhancement is needed for "Copy to Clipboard" for better UX](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/410#issuecomment-1893590773)
- [x] [Settings Page > The color of the font should be ~black~ grey.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/410#issuecomment-1893610493)
- [x] [The border bottom is not present when `Settings` is collapsed.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/410#issuecomment-1893621916)
- ~[Debug bar does not disappear even when the CDP switch is off](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/410#issuecomment-1893651430)~
- [x] [The Information panel should be collapsible](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/410#issuecomment-1893709500)
- [x] [Unexpected behaviour with multi tab processing under the given scenario](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/410#issuecomment-1894968756) 
- [x] [The icons are not visible in light theme](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/410#issuecomment-1895461905)
- [x] [PSAT settings icon seems bit bigger](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/410#issuecomment-1897791476l)
- [x] [Feedback on icons padding](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/410#issuecomment-1897809382)
- [x] [Implement Hand Pointer for Collapsible **System Information** in Alignment with Settings Section](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/410#issuecomment-1897815356)

**Comment by kjnanda** [comment]
Consider a scenario where the CDP switch is turned ON, and the user clicks on the **Analyse this tab** button. However, within 4-5 seconds, the user switches it OFF. In most cases, PSAT effectively handles this scenario, but occasional issues have been identified as mentioned below:

1. The debugger notification sometimes fails to disappear and stays forever. It stays even while opening the new tab though the switch is off.
2. The blocked cookie count does not reset to zero. Ideally, when the debugger is not attached, it shouldn't fetch blocked cookie information.
3. The sidebar only displays only 2 frames: the Top main frame and Unknown frames.

@amovar18 Could you kindly debug these issues? Additionally, it has been noted that other tabs also exhibit inaccurate results in this particular case.

 I have found this use case but I was unable to capture the visual as it appears randomly.

**Comment by amedina** [comment]
In principle the Info Bar (IB) needs to be closed explicitly by the user. The use case for PSAT entails the user swiching off PSAT's use of CDP, and manually closing the IB. After that the IB won't show up again. 

Once the user switches CDP off, PSAT will refresh the loaded page and the whole Blocked Cookies section the Cookies landing page will be rendered.

**Comment by kjnanda** [comment]
PSAT does not work as expected when the CDP switch is turned off under the following conditions:

1. Turn on CDP switch form the Popup.
2. Observe the appearance of the debug bar and the page refreshing.
3. Now, cancel the debug bar.
4. Turn off the CDP switch.
5. Observe that the page is not refreshed, resulting the data displayed from the previous state.

-----

**Please check the visual attached.**

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/45cdcb68-53b0-4723-b038-ee31dc311757

----

**Please check the screenshot.**

<kbd>![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/62c6497c-4be1-42d5-994f-10dc6bdfdb2c)</kbd>

**Comment by kjnanda** [comment]
Scenario: Testing the CDP switch on/off operation with **multiple tabs.**

As per the expected behaviour when the switch status is toggled, a page refresh must occur. However, this functionality does not synchronize properly when multiple tabs are in use. Please consider the scenario when one tab _displays a blocked cookie with the switch off,_ toggling the state refreshes the page, but the cookies landing page does not refresh, resulting in inconsistent outcomes. Additionally, it has been observed that the cookie count does not reset and it continues from where it left off.

**Please check the below visual**
https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/3ae8688e-f351-42cf-9cf1-55d8caaadf57

**Comment by kjnanda** [comment]
After refreshing the page, it has been observed that the cookie count resets to "0". As a user, one would expect the count to increase gradually. However, the current behavior results in a sudden change to a large number, for e.g from 0 to 37 which should be prevented.

**Please check the below visual.**

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/925a74f0-4a6f-4391-8841-11e5546fbfc9

**Comment by amovar18** [comment]
@kjnanda as for the last Issues reported its because the page is loaded 2nd time and the cookies are already set in the browser that's why you see the jump in the cookie count.

**Comment by kjnanda** [comment]
Upon switching from multiple tabs to a single tab, the expected behavior is for the "Analyse this tab" button to appear on all open tabs. However, an occasional bug has been observed where one of the tabs continues to display the cookie. Upon repeating the process, the button appears as expected. This issue does not consistently manifest, but the following test environment details may help in debugging:

1. Open a new Chrome profile
2. Open a new tab and enter the URL
3. Repeat the same process for 2 or 3 additional tabs
4. Navigate to PSAT options and switch the setting from Single tab to Multi tab
5. Note that each tab will display the cookie
6. Revert the settings from multi tab to single tab
7. Observe that one of the tabs (usually the first tab) displays the cookies instead of the "Analyse this tab" button
8. Repeat steps 4-7 and note that the same scenario does not occur

**Please refer to the provided visual.**


https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/d387ddc1-2409-4fe1-8a2f-dccb4c7d85f3

**Comment by kjnanda** [comment]
The UI element is intuitive which clearly indicates its switch functionality with a visual effect of both the 'On' and 'Off' states. Considering this, is it necessary to incorporate a separate label as 'Switch On' or 'Switch Off'?

<kbd>![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/7bef9e55-c6b7-4c5e-a712-e54b3fe88698)</kbd>

**Comment by kjnanda** [comment]
I've noticed that the tool requires more time than anticipated to display cookies. Also, there is an issue where it occasionally indicates '0' number for cookies. 
Please refer to the attached screenshot, which illustrates that 'https://www.livemint.com/' site shows `0` FPCs, while the stable version consistently provides the accurate count of cookies. This situation may also occur for 3PCs or Blocked Cookies.

> [!NOTE]
> This has been noticed in multi tab environment only.

<kbd>![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/d2956755-bec4-4df9-bf8b-4cdf7749bd05)</kbd>

----

Please check the below visual:

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/271d3c47-6bfd-42ae-9729-7b1280fe36da

**Comment by kjnanda** [comment]
@amovar18 Ref: https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/410#issuecomment-1886488005

> because the page is loaded 2nd time and the cookies are already set in the browser that's why you see the jump in the cookie count.
Got it. 

But I have a query when I opened up the website for the first time the cookie count got increased from 1 to 24/25. Is there any chance of improvement in this case?

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/50e1211f-5a31-45c3-a077-d0aa8a07dfb0

_PS: The above scenario was QAed with the latest code pull from the given branch._

**Comment by amovar18** [comment]
> But I have a query when I opened up the website for the first time the cookie count got increased from 1 to 24/25. Is there any chance of improvement in this case?

I don't think so because if a single request has that many cookies then the count will definitely appear like that. SInce all of them are added to the database in a single update.

**Comment by kjnanda** [comment]
There is a noticeable jumping effect while toggling the setting from DevTools for CDP Swtich. 

**Please refer to the visual shared below.**

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/15aac9e6-4acf-4668-96d8-e237ef9db546

**Comment by amovar18** [comment]
@kjnanda that might be because CDP debugger bar appears and extension page is pushed a bit down it was noticeable before is because the switch was in the popup. Could you check if the jumping effect is still there if cdp is toggled from popup.

**Comment by kjnanda** [comment]
@amovar18 There's a need for improvement in copy to clipboard. Currently, when the "Copy to Clipboard" button is clicked -

- [ ]  It does not give any effect if the click event has happened or not.

- [ ] The content gets copied, but there's no indication or message confirming the action. It would be good to display a message or some visual feedback to inform users that the content has been successfully copied.

- [ ] When the copied content is pasted, its alignment does not look  intuitive to me

<kbd>![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/4436a363-4e42-405a-af22-9f725289de2b)</kbd>

**Comment by kjnanda** [comment]
Settings Page > The color of the font should be black.

<kbd>![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/dc1862b9-0626-4392-b369-e31673e677d9)</kbd>

**Comment by kjnanda** [comment]
The border bottom is not present when `Settings` icon is collapsed.

---

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/90309613-5874-4aa0-8c17-0153f3fa2388

----

<kbd>![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/0afaec21-8b7d-46f4-a659-46db89e8691f)</kbd>

**Comment by kjnanda** [comment]
After successfully attempting multiple clicks in the pop-up, along with toggling the PSAT DevTools Panel for CDP switch, it became unresponsive to further toggle events. Changing the switch state was no longer effective, and the debug bar did not disappear when the switch was turned off.


https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/33102b3f-8111-4f17-8788-1f4bd6331b78

**Comment by kjnanda** [comment]
The information menu should collapsible. I don't see the relevant drop down button.

<kbd>![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/b44beca0-5d00-4161-b6fd-95b60335cde0)</kbd>

**Comment by amovar18** [comment]
@kjnanda the last item wasnt mentioned as being collapsable.

**Comment by kjnanda** [comment]
@amovar18 Could you please take a look at the design shared with us? I see the arrow over there. So considering that part I was looking for collapsible drop down. 💭 

<kbd>![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/63d25722-6ef4-404b-817b-2e5b49c4b8ab)</kbd>

**Comment by kjnanda** [comment]
@amovar18 Please check the below comment with ref to https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/410#issuecomment-1893590773

This does not show any distinction between the title and content that goes under the column header. May be should we keep the title in bold?

<kbd>![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/0e1f7abf-130b-4fd4-b126-b2e1969fe674)
</kbd>

**Comment by kjnanda** [comment]
@amovar18 I have found some unexpected cookie behaviour with multi tab processing under the given scenario.

**Steps:**

1. Open three different tabs and navigate to the specified URLs.
2. Activate the Chrome DevTools Protocol (CDP) mode and analyze one of the tabs.
3. Enable multi-tab processing using the switch provided in the settings.
4. Now, deactivate the CDP mode.
5. This will reload the page and will show the cookies other than blocked cookies.
6. Now, disable the multi-tab processing.
7. Observe that one of the tabs still displays a count on the cookie pop-up jar, which is not the expected behavior.

Now, please check the below visual. Here, please observe that when I keep the some delay in toggling the switches this works find but I try to perform the actions immediately then it ends up with cookie count on popup cookie jar and the count then remains forever. 

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/70512a91-48da-497a-8293-6b7dfc61f6e9

**Comment by kjnanda** [comment]
THe icons are not visible in light mode. 

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/2b1db5d3-9b25-4335-9c97-6ff338479686

**Comment by kjnanda** [comment]
@amovar18 PSAT sidebar icon needs to be bit smaller than the current size. Please refer to the screenshot below.

<kbd>![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/dce5159a-e5b9-42a2-bca7-f06326da7d7e)
</kbd>

**Comment by kjnanda** [comment]
@amovar18 Please check the pointers wrt to the number mentioned in the screenshot.

1. It seems there is more gap between the icon and title. Can we reduce a bit?
2. I collapsible button needs padding from right side.

<kbd>![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/a3dade43-fae8-4db4-af13-bdff45c65a8f)</kbd>

**Comment by kjnanda** [comment]
@amovar18, As the system information is collapsible, it would enhance user experience to include a hand pointer upon hovering over it. I've shared a visual below. Please observe how the hand pointer is utilised in the Settings section; I recommend implementing a similar behavior for the system information as well.


https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/36a7538c-e96e-448e-811e-a504457201e1

**Comment by maitreyie-chavan** [comment]
Addressed and released as a part of [v0.5](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.5.0)
