### ISSUE TITLE
[QA] - CLI decoupling - Save analysis results in a directory

### ISSUE THREAD

**Issue by pavanpatil1** [GoogleChromeLabs/ps-analysis-tool#412]
@ayushnirwal Checked the CLI decoupling PR and Observed few issues added below: 

- [x] <a href="https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/412#issuecomment-1886418957">In the affected-cookies.csv file the technologies are visible. It should show only the affected cookies.</a>
- [x] <a href="https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/412#issuecomment-1886419183">Error is visible while executing the CSV file.</a>

- [x] <a href="https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/412#issuecomment-1886419510">If dir not exist can we create a directory by taking users permission</a>

**Comment by pavanpatil1** [comment]
- [ ] In the affected-cookies.csv file the technologies are visible. It should show only the affected cookies. 


![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/93aa5776-4cb2-444a-b615-f89e6a02386f)

**Comment by pavanpatil1** [comment]
- [ ] For the multiple site input cases for the CSV file error is visible. Also, it is not asking for number of URL to analyze in CSV file it is taking all URLs. 

![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/504dc743-68ac-4f4f-9d2b-0315be091522)

**Comment by pavanpatil1** [comment]
- [ ] **Suggestion:** If the provided directory is not present can we create a directory and add the files inside that?. Currently, If directory is not present on machine then this message is visible - "Provided dir test does not exist" so if it's not present could we create it?

![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/422aedb7-8ad1-461f-882c-a2349fd93231)

**Comment by maitreyie-chavan** [comment]
Addressed as a part of [v0.5](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.5.0)
