### ISSUE TITLE
[QA] Performance optimization branch 

### ISSUE THREAD

**Issue by kjnanda** [GoogleChromeLabs/ps-analysis-tool#444]
- ~[Issue with multitab and extension refresh](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/444#issuecomment-1905649275)~ - This is separately mentioned [here](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/462) so removing it.
- [x] [Can we improve the time the pop up takes to display the cookie count?](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/444#issuecomment-1905444410)
- [x] [The random behaviour while loading the frames](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/444#issuecomment-1905488085)
- [x] The Refresh panel button takes longer time to appear. _It is better now_
- [x] [Shows multiple errors on chrome://extensions page](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/444#issuecomment-1905663020)
- [x] ~[Copy button's functionality is not working.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/444#issuecomment-1905686476)~ Removing this as this works as expected on Google Doc
- [x] [Cookie count issue with pop up and unresponsiveness during single tab env](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/444#issuecomment-1905699863)
- [x] [Switching from multi tab to single tab and clicking on "Analyse this tab" button throws the error on chrome://extesions page](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/444#issuecomment-1905692750)
- [x] [Opening the website on fresh profile shows the preloaded frames with Analyse this button present.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/444#issuecomment-1906001409)
- [x] [PSAT fails to showcase the cookies landing page when user clicks on "Analyse this tab" button using using popup](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/444#issuecomment-1907455993)
- [x] [Cookie are not appearing.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/444#issuecomment-1907552385) _This issue is found to be very random._
- [x] [Issue with page refresh and debug bar](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/444#issuecomment-1907829053)
- [x] [blank table issue](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/444#issuecomment-1909476743)
- [x] [Multiple errors for frame on extension page after using extension reload functionality](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/444#issuecomment-1909498836)
- [x] [Warning about `Maximum update depth exceeded` on chrome://extension page](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/444#issuecomment-1909913494)
- [x] [CDP switch is not working as expected.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/444#issuecomment-1916431882)
- [x] [Extension crashes when multi tab is enabled](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/444#issuecomment-1918604160)

PR #436

**Comment by kjnanda** [comment]
Consider the following scenarios:

- Load the chrome profile with extension from dev branch
- Perform the some actions in 2-3 browser keeping the multi tab mode one
- Now, switch the branch to `feat/optimize-iterations` branch
- Refresh the extension page from chrome://extension page
- Now, check the each tab and it would show `Refresh panel` button - It takes few secs to show up this buuton
- Now, click on the this button
- Observe that after clicking on this button with multitabs mode on, it should show the cookies on each page. However, right now, it shows cookie with `0` count and sidebar frames are not appearing

Please refer to the below visual.


https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/4074e1b2-9954-4c45-9209-a8c5b68a3bbc

**Comment by kjnanda** [comment]
Can we improve the time the pop up takes to display the cookie count?

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/22996715-599f-4c90-9ad7-b1f51c3ead10

**Comment by kjnanda** [comment]
@amovar18 [This](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/444#issuecomment-1905384808) is partially fixed. 

Please refer to the visual below where it shows the frames but the cookies are not appearing. Cookies count is still `0`. Also, observe that the debug also not present though CDP switch is on.

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/e5de91b4-9b99-4826-aa4f-fd269f789a9b

**Comment by kjnanda** [comment]
Shows multiple errors on chrome://extensions page while switching on/off the settings for CDP and multi tab

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/a97a9a08-ed69-43d8-8434-8f061991d728

----

<img width="469" alt="Screenshot 2024-01-23 at 15 06 44" src="https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/147c8dc0-35ba-4da9-ab60-79b296d3f106">

**Comment by kjnanda** [comment]
Copy button's functionality is not working.

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/7201b19d-8370-44ca-bea6-93630d0eaba1

**Comment by kjnanda** [comment]
Switching from single tab to multi tab and clicking on "Analyse this tab" button throws the error on chrome://extesions page


https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/635bf5ea-809a-4d1b-ab8a-69584eca913c


---

<img width="694" alt="Screenshot 2024-01-23 at 15 26 01" src="https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/a78aee69-eab1-4ebe-a729-be71c54a6cb3">

**Comment by kjnanda** [comment]
Switching from multi tab to single tab -> The tab which is not being analysed still shows the cookie count in popup cookie jar.

Also, I felt that the browser became little bit unresponsive in between. 

----

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/3645af6b-1050-45c4-b9a0-18365e4e2c2f

**Comment by kjnanda** [comment]
Opening the website on fresh profile shows the preloaded frames with `Analyse this button` present.


https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/4ffb01eb-78bc-4e73-82fa-cd542d843a05

**Comment by kjnanda** [comment]
@amovar18 The fix added for this is not working as expected. Please check the below visual.

The latest commit - b3595d3


https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/b819c619-1610-4cbd-a799-7909fc740df3

**Comment by kjnanda** [comment]
@amovar18 When user switches from multi tab to single and clicks on "Analyse this tab" button from **Pop up**, PSAT fails to show case the cookies landing page.


https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/68cbdbd8-1636-4140-9220-5937ebe61655

**Comment by kjnanda** [comment]
@amovar18 Please check this 

<img width="1386" alt="Screenshot 2024-01-24 at 12 59 35" src="https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/aecaea4b-a447-4925-9396-472d17da348f">

----


https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/92c304e4-e827-42d4-a473-4f0000813682

**Comment by kjnanda** [comment]
@amovar18 Issue with page refresh

So when I try to enable the CDP switch either from the popup or PSAT DevTools, I have noticed 2 issues:

1. The page is not refreshed
2. THe debug does not appears

Note that this issue is present for the very first time only. 

Please check the screencap below

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/6b2b7b38-0776-400c-aceb-4636d3bb5ce1

**Comment by kjnanda** [comment]
It shows the blank table for a 2-3 sec while the data is being fetched

<kbd>![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/77a680b8-7b99-41db-8987-a7f823c3e75d)</kbd>

**Comment by kjnanda** [comment]
I see many errors on extension's page when I reload the extension with multi tab env.

Steps:

1. Open a new chrome profile
2. Open chrome://extensions on very first tab
3. Open 2-3 URLs in the next tabs
4. Now, enable the multi tab from the settings
5. Reload the extension
6. Go back to URLs those were open
7. Observe the DevTools which will show `Refresh Panel` button
8. Click on it
9. Observe that the cookies are not visible until you refresh the page
10. Now, as soon as you refresh the page, extension page throws errors

Please refer to visual below

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/bcd110fb-aef6-4d13-8a59-711ad57c7b06

**Comment by kjnanda** [comment]
Warning about `Maximum update depth exceeded` on chrome://extension page

<kbd><img width="558" alt="Screenshot 2024-01-25 at 16 15 46" src="https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/e886a803-b473-49be-8d65-7d9c83cfed1c"></kbd>

**Comment by kjnanda** [comment]
@amovar18 With the latest code pull from `feat/optimize-iterations` branch, I encountered the following issues:

commit id - 9c54aa91a046a5be5cab2cd7564f867da9561c42

Though the CDP switch is on 
- Debug bar is not visible
- Blocked cookies count stays `0`
- No indication of cookies blocked with yellow bg color

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/aecea082-7c43-40da-af34-d4dc1bb952b5

**Comment by kjnanda** [comment]
Extension crashes when multi tab is enabled.

Commit Id - 73800544ae504a5edf892c91d9dee7368018b8f2

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/2d25b68d-2205-4afd-847c-619364b7039e

**Comment by kjnanda** [comment]
This has been addressed in V.0.5.0 Release.
