### ISSUE TITLE
Small changes

### ISSUE THREAD

**Issue by gagan0123** [GoogleChromeLabs/ps-analysis-tool#459]
Following is the list of small changes that were requested across various sync-up calls
- [x]  [In the cookies tab, remove the text "This tool works best with a single tab for cookie analysis."](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/459#issuecomment-1915651322)
- [x]  [Rename "Unknown Frame(s)" to "Unknown Frames"](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/459#issuecomment-1915651560)
- [x]  [Remove unknown frames unless there are cookies in the unknown frame section](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/459#issuecomment-1915651793)
- [x]  [Change the frame count to 1 if no cookies belong to "Unknown Frames"](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/459#issuecomment-1915652034)
- [x] [Add a period towards the end of the Multitab Debugging messaging under Settings.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/459#issuecomment-1920504369)
- [x] [Include Wiki links for in Enabling CDP & Multitab Debugging sections.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/459#issuecomment-1921020177)
- [x] [Update multi-tab setting description](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/459#issuecomment-1921021202)
- [x] [Fix the Wiki link reference mentioned under the Blocked Cookies section on the cookie landing page.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/459#issuecomment-1921021857)

**Comment by gagan0123** [comment]
The selection color needs to change in the cookies table, as you cannot determine what color it was before you selected it.

**Comment by gagan0123** [comment]
In the cookies tab, remove the text "This tool works best with a single tab for cookie analysis."

**Comment by gagan0123** [comment]
Rename "Unknown Frame(s)" to "Unknown Frames"

**Comment by gagan0123** [comment]
Remove unknown frames unless there are cookies in the unknown frame section

**Comment by gagan0123** [comment]
Change the frame count to 1 if no cookies belong to "Unknown Frames"

**Comment by mayan-000** [comment]
Add a period towards the end of the Multitab Debugging messaging under Settings.

**Comment by mayan-000** [comment]
Include Wiki links for in [Enabling CDP](https://github.com/GoogleChromeLabs/ps-analysis-tool/wiki/PSAT-Settings-and-Permissions#enabling-chrome-devtools-protocol-in-psat) & [Multitab Debugging](https://github.com/GoogleChromeLabs/ps-analysis-tool/wiki/PSAT-Settings-and-Permissions#multi-tab-debugging) sections.

**Comment by mayan-000** [comment]
Update multi-tab setting description to
- The PSAT tool is designed for efficient single-tab analysis. While [multi-tab debugging](https://github.com/GoogleChromeLabs/ps-analysis-tool/wiki/PSAT-Settings-and-Permissions#multi-tab-debugging) is available for more comprehensive analysis, it is intended for examining 2-3 tabs simultaneously. Using more tabs may impact the tool's responsiveness.

**Comment by mayan-000** [comment]
Fix the Wiki link reference mentioned under the Blocked Cookies section on the cookie landing page.

**Comment by maitreyie-chavan** [comment]
Addressed and released as a part of [v0.5](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.5.0)
