### ISSUE TITLE
[QA] Errors found on chrome://extensions page

### ISSUE THREAD

**Issue by kjnanda** [GoogleChromeLabs/ps-analysis-tool#461]
I have found below errors on chrome://extensions page

```
Test Environment:
1. Chrome - 121.0.6167.85 (Official Build) (arm64) 
2. Branch - feat/optimize-iterations
```
-----

- [x] [Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/461#issuecomment-1916149007)
- [x] [Uncaught (in promise) Error: Extension context is invalidated](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/461#issuecomment-1916177652)
- [x] [Uncaught (in promise) Error: No tab with id: 250142296.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/461#issuecomment-1916197877)
- [x] [Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.%s](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/461#issuecomment-1916372144)

**Comment by kjnanda** [comment]
Please refer to the visual below.

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/81eda7c4-f5f3-4b4e-bb56-a31cb15c0349


Screenshot :

![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/0f64a30b-543f-4e2b-94a0-aa40e49805ef)

**Comment by kjnanda** [comment]
<kbd>![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/a8e33c02-73f1-447a-97c9-ab5d36843e6b)</kbd>

**Comment by kjnanda** [comment]
While changing the branch and reloading the extension throws the errors on chrome://exntesion page

----

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/2e7b32b2-af54-415e-abae-69f627303460

-----

<kbd>![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/aebc2a33-f023-4d1b-9301-ab01ea06c26b)</kbd>

**Comment by kjnanda** [comment]
This issue reappeared 

<kbd><img width="519" alt="Screenshot 2024-01-30 at 14 33 40" src="https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/4a50d6e3-98a1-4772-9b9c-2f4c521d6aa0"></kbd>

**Comment by pavanpatil1** [comment]
This issue has been fixed, and no errors are visible on the extension page now. Therefore, closing this issue.
