### ISSUE TITLE
[QA] Dev Branch

### ISSUE THREAD

**Issue by kjnanda** [GoogleChromeLabs/ps-analysis-tool#471]
- [ ] [Issue with GSI feature on CNN site](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/471#issuecomment-1926242443)
- [x] [Error: Uncaught (in promise) Error: No tab with id: 363275767.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/471#issuecomment-1926247808)
- [x] [CDP switch and `0` cookies issue](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/471#issuecomment-1926262221)
- [x] [Error: Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'newUpdates')](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/471#issuecomment-1926263364)
- [ ] [Blank Table and blank screen issue](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/471#issuecomment-1926303921)
- [x] [Regression bug : Existing core functionality is breaking](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/471#issuecomment-1926330707)
- [ ] [PSAT CLI - Samesite does not show any value. It is empty.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/471#issuecomment-1931678169)
- [x] [CLI: In the "Technologies" frame, the description is not clearly visible.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/471#issuecomment-1931664917)
- [x] [CLI: If there is no description present for any technology then the proper message should be visible.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/471#issuecomment-1931666270)
- [x] [CLI: The EXP date column shows wrong format for some cookies.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/471#issuecomment-1931662032)
- [x] [Blocked cookie are not appearing Yellow BG color in CLI Dash board.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/471#issuecomment-1932020955)
- [ ] [PSAT Extension - The "Unknown frames" is visible with URL rewrite.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/471#issuecomment-1932016503)

**Comment by kjnanda** [comment]
Issue with GSI feature on CNN site

When I opened the CNN website with single tab mode, it kept processing but the GSI feature was not found. When I inspect the tool it threw the below errors on console.

<kbd><img width="1470" alt="Screenshot 2024-02-05 at 10 27 35" src="https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/7d5db8a2-c1ad-4781-9a73-608e853e0fcd"></kbd>

This started working as expected when I opened one more new chrome profile.

**Comment by kjnanda** [comment]
Uncaught (in promise) Error: No tab with id: 848821757.

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/82eccbb4-2d13-40e1-afbf-0473ddce9cb6

**Comment by kjnanda** [comment]
CDP switch issue

Steps:

1. Open chrome://extension tab
2. Now, open 2-3 tabs with different URLs 
3. Enable CDP and you must see the debug bar
4. Anlyse the different tabs in single tab environment and observe correct set of data should appear as CDP is enable. E.g. Blocked cookie, Yellow BG color etc
5. Now, Keep checking the chrome://extensions tab for any errors 
6. Close each tab one by one and you will notice the error as mentioned [here](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/471#issuecomment-1926247808).
7. Now, repeat step 2 and observe that 
         - the debug bar is not reappearing
         - No blocked cookies
         - No other cookies getting loaded
         - Cookies landing page shows `0` cookies
         - CDP switch is still on but you won't get above thing
         
-----

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/295b2d7c-6170-4302-a0e3-556a4d75e4e5

**Comment by kjnanda** [comment]
Error: Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'newUpdates')

<kbd><img width="683" alt="Screenshot 2024-02-05 at 11 02 47" src="https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/366191e2-9727-4fd8-9d79-bf8a87f67a08"></kbd>

**Comment by kjnanda** [comment]
Blank Table and blank screen issue

When I toggle the setting - multi tab and/or CDP; the blank table and blank screen issues are still visible. Especially with multi tab environment.

----

Multi tab - 

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/a59a66b4-efcc-46e6-ab2c-bd7955b9d77a

-----

Single Tab - 

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/439347d9-f5b4-412a-a1d6-e9d19ab00945

**Comment by kjnanda** [comment]
Regression bug : Existing core functionality is breaking

As per the expected behaviour if the URLs in next to chrome://extensions page or if it is tab num - 2 then it should by default load the cookies. However, wit this branch this functionality is breaking. 

Steps:
1. Checkout to develop branch > Pull the code > Run npm start
2. Open a new chrome profile and install the extension
3. Open a new tab with any URL
4. Observe that it loads cookies as soon as you hit the URL
5. Now, close the tab and again open the new tab with any URL
6. Observe that this time it does not load the cookie and shows "Analyse this tab" button instead


https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/6b0d1142-d299-4136-acd5-5c7d63102011

**Comment by pavanpatil1** [comment]
Regression bug : Copy to clipboard is not working. 

On the click of "Copy to clipboard," the content fails to copy. Furthermore, upon pressing Ctrl + V, the content does not appear.

[copytoclipboard.webm](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/d127fb81-c82c-4792-a8b5-55bfaca7a7b0)

**Comment by mohdsayed** [comment]
@kjnanda 

The infinite loading issue was fixed in https://github.com/GoogleChromeLabs/ps-analysis-tool/pull/478 and QA tested by Pavan.

We cannot replicate the false positive issue on CNN after several attempts so we will handle in later.

**Comment by pavanpatil1** [comment]
CLI: If there is no description present for any technology then the proper message should be visible. 


![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/5a736960-770a-4fc1-bc3c-72a32359c991)

**Comment by kjnanda** [comment]
PSAT CLI - Samesite does not show any value. It is empty.

| PSAT CLI | PSAT Extension | 
|--- |---|
| ![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/21573d2a-13c2-4637-a1c3-b77becf5f0c7) | ![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/22737ebc-7f21-49f0-8570-349abfe52001) |

**Comment by kjnanda** [comment]
@ayushnirwal Blocked cookies are not appearing Yellow BG color in CLI Dash board.

<kbd><img width="1464" alt="Screenshot 2024-02-07 at 18 38 27" src="https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/9505a9e6-201c-4392-a351-d2d6210aa667"></kbd>

**Comment by pavanpatil1** [comment]
> https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/471#issuecomment-1932016503

Hi @amovar18, It is still reproducible on the develop branch. 


Check the below steps: 

1. Go to bbc.com and open the cookies frame. 
2. Now, rewrite the URL to example.com and check the unknown frames will be shown. It should not be displayed. 
3. Now, refresh the page the page will be refreshed and unknown frame frame will be gone but cookies will be displayed. 

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2024.02.13-13_46_32.webm](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/f8745706-3d61-48e4-a595-1120bf85e394)

**Comment by pavanpatil1** [comment]
Hi @amovar18, still able to replicate [this](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/471#issuecomment-1932016503) issue.


![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/907c44c2-6ebc-44ea-a855-f14a03f1171c)

**Comment by amovar18** [comment]
@pavanpatil1 the issue is replicated is different than what you have shown, because the issue that was listed shows unknown frames in the sidebar which have been removed in 0.6.0.

**Comment by pavanpatil1** [comment]
The unknown frames have been removed and other issues have been resolved. Hence closing this issue
