### ISSUE TITLE
[QA] - Reload all tabs option

### ISSUE THREAD

**Issue by pavanpatil1** [GoogleChromeLabs/ps-analysis-tool#496]
- [ ] [The **Reload All** button padding and margin is not matching the **Relaunch** button. ](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/496#issuecomment-1945706838)

- [ ] [There should be consistency between the "Reload" button in the popup and the developer tool.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/496#issuecomment-1945707524)

- [ ] [The settings gets changed on all the tabs without reloading the page. ](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/496#issuecomment-1945708381)

- [ ] [If switch the settings to multi tab, then on the cookie landing page the cookies details are visible without clicking on reload all button. ](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/496#issuecomment-1945709195)

- [ ] [Errors are visible on the extension page](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/496#issuecomment-1945709518)

- [ ] [The toast message takes time to adjust its position when resizing the devtool screen.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/496#issuecomment-1945709979)

- [ ] ["Reload All" / "Analyze this tab" button won't work after relaunch the browser.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/496#issuecomment-1947674211)

**Comment by pavanpatil1** [comment]
The padding and margin of the "Reload All" button do not align with those of the "Relaunch" button.

Actual  result          |  Expected result
:----------------:|:-------------------------:
![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/a5b5c600-3a0b-4ee9-96d3-44fd1a7255e9)| ![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/74fb9bb0-c566-404d-b6f7-e4018dddcf98)

**Comment by pavanpatil1** [comment]
There should be consistency between the "Reload" button in the popup and the developer tool.

![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/9d6fec92-1262-441d-9997-8ed137d60180)

**Comment by pavanpatil1** [comment]
The settings gets changed on all the tabs without reloading the page.


**Steps to reproduce:** 

1. Open multiple tabs and enable the CDP.
2. Observe on all the other tabs the CDP gets automatically enabled. 


[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2024.02.15-14_30_05.webm](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/d40932a6-d58e-44c2-8dc6-49e4b5987380)

**Comment by pavanpatil1** [comment]
If switch the settings to multi tab, then on the cookie landing page the cookies details are visible without clicking on reload all button.


**Steps to reproduce:** 

1. Open 2-3 tabs an visit to different sites. 
4. Now, from first tab navigate to settings and enable the multi tab debugging. observe the toast message will be visible to reload all the pages. 
5. Without clicking on it navigate to other tabs and observe the cookie landing page. 


[multitab.webm](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/ceb3695a-6afa-4939-a94a-96086cf19c67)

**Comment by pavanpatil1** [comment]
Errors are visible on the extension page

![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/f3b1e661-1f08-4171-a7e5-12a2e02d1ad2)

**Comment by pavanpatil1** [comment]
The toast message takes time to adjust its position when resizing the devtool screen.

[screensize.webm](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/66cab989-d9c7-448b-accd-d7edde2c751b)

**Comment by pavanpatil1** [comment]
- [ ] "Reload All" / "Analyze this tab" button won't work after relaunch the browser. 

After relaunch the browser the reload all and analyze this tab button not work. 


**Steps to reproduce:** 

1. Open the Privacy sandbox tab from devtool and observe all the cookies are visible. 
2. Now, open the "chrome://flags" and change the settings and click on "Relaunch" 
3. Visit the Privacy sandbox tab in devtool and enable the CDP and click on "Reload all tabs" button. 

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2024.02.16-08_09_05.webm](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/f42a0b8c-d022-49cb-91b8-a37621e304bb)

**Comment by pavanpatil1** [comment]
Verified the issue and it seems fixed and working fine on main branch. Hence closing this issue.
