### ISSUE TITLE
[QA] - Updated UI for cookies blocking status

### ISSUE THREAD

**Issue by pavanpatil1** [GoogleChromeLabs/ps-analysis-tool#508]
- [x] [If the cookies no blocked reason found then the message should be displayed properly. Currently, it shows that message in the description box but it not properly visible. Some extra top padding is visible. ](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/508#issuecomment-1952291877)

- [x] [In the default mode, without enabling the CDP mode the blocked cookies are visible. ](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/508#issuecomment-1952292236)

- [x] [Number of cookies with not identifying blocking status are more. ](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/508#issuecomment-1952300820)

**Comment by pavanpatil1** [comment]
- [ ] If the cookies no blocked reason found then the message should be displayed properly. Currently, it shows that message in the description box but it not properly visible. Some extra top padding is visible. 

![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/3b9bcf98-9802-49af-901b-e059750dae98)

**Comment by pavanpatil1** [comment]
There are more cookies with unidentified blocking statuses, all of which are visible as expired.

![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/ae8ef318-11bd-4c78-b1cb-2be40eac1861)

**Comment by pavanpatil1** [comment]
Issues are fixed. Hence closing this issue
