### ISSUE TITLE
[QA] - Develop branch

### ISSUE THREAD

**Issue by pavanpatil1** [GoogleChromeLabs/ps-analysis-tool#515]
- [x] [The background color of the allowed domain is not persist. It not visible for sometime. ](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/515#issuecomment-1954005683)

- [x] [There should not be extra padding before the cookie blocking response message. ](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/515#issuecomment-1954006058)

- [x]  [In the CLI, In the affected cookies section - The blocked reason for the cookies is not visible.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/515#issuecomment-1954019496)

- [x]  [In CLI, For the cookies which are not blocked the blocked status is visible ](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/515#issuecomment-1954025667)

- [x]   [In CLI, Technology frame values are visible in yellow background.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/515#issuecomment-1954036683)

**Comment by pavanpatil1** [comment]
- [ ] The background color of the allowed domain is not persist. It not visible for sometime. 

**Steps to reproduce:** 
1. Enable the CDP and from cookie frame allow any domain. 
2. Go to another frame and come back to frame where allowed the domain. 
3. Observe the color. 

[allowlistissue.webm](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/d967d576-48d8-4ab3-80ef-369c472fa078)

**Comment by pavanpatil1** [comment]
- [ ] There should not be extra padding before the cookie blocking response message. 

![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/effb939f-4f2c-446a-b158-1278e158cd76)

**Comment by pavanpatil1** [comment]
- [ ] In the CLI, In the affected cookies section - The blocked reason for the cookies is not visible. 

![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/13b54e2d-387b-40b7-b30c-8169a0cfa02d)

**Comment by pavanpatil1** [comment]
- [ ] In CLI, In the unknown frames - The newly added icon is visible. It should not be visible in CLI




![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/3f233883-c339-482e-b979-97b098a667f9)

**Comment by pavanpatil1** [comment]
- [ ] In CLI, Technology frame is visible in yellow background. 

![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/ddaca953-0f2c-4d99-9f47-36a2ba443436)

**Comment by mohdsayed** [comment]
The issue was fixed in https://github.com/GoogleChromeLabs/ps-analysis-tool/pull/518

**Comment by pavanpatil1** [comment]
All issue are fixed and merged. Hence closing this issue
