### ISSUE TITLE
[QA] - Refactor Service Worker and UI 

### ISSUE THREAD

**Issue by pavanpatil1** [GoogleChromeLabs/ps-analysis-tool#521]
- [ ]  [The functionality of the "Reload" button appears to be non functioning properly. Clicking on it does not trigger the expected action of reloading the page.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/521#issuecomment-1959351804)

- [ ] [The "Analyze This Tab" button is not working properly. On click on it the page gets reloads as intended but the button remains visible. ](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/521#issuecomment-1959353283)

- [ ] ["Export Cookies" button not visible properly. ](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/521#issuecomment-1959354164)

- [ ] [In the command-line interface (CLI), the blocked reason for the cookies is not visible.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/521#issuecomment-1960663498)

- [ ] [When users switch back to single-tab processing, the "Analyze This Tab" button is not be visible on all tabs.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/521#issuecomment-1960756709)

**Comment by pavanpatil1** [comment]
The functionality of the "Reload" button appears to be non functioning properly. Clicking on it does not trigger the expected action of reloading the page.


[reload.webm](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/104c9dd3-208f-4b9d-a7fd-3acf78ecfc91)

**Comment by pavanpatil1** [comment]
The "Analyze This Tab" button is not working properly. On click on it the page gets reloads as intended but the button remains visible.


[analyzethis button.webm](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/f02edd25-445f-4eb3-8958-bd913711c74c)

**Comment by pavanpatil1** [comment]
"Export Cookies" button not visible properly.


![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/212b07e4-117d-4b70-9306-c773a16938c4)

**Comment by pavanpatil1** [comment]
In the command-line interface (CLI), the blocked reason for the cookies is not visible.


![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/a52102f1-3c9c-4b89-a51f-f76b6047f43d)

**Comment by pavanpatil1** [comment]
When users switch back to single-tab processing, the "Analyze This Tab" button is not be visible on all tabs. 


[analyze.webm](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/980dabb2-bf56-4511-96b3-a7e51462d2ff)

**Comment by pavanpatil1** [comment]
Closing this issue as fixed.
