### ISSUE TITLE
Use chrome.i18n infrastructure to localize PSAT

### ISSUE THREAD

**Issue by amedina** [GoogleChromeLabs/ps-analysis-tool#566]
PSAT, CLI: use the chrome.i18n infrastructure to implement internationalization across PSAT.

**Comment by pavanpatil1** [comment]
Hi @mayan-000, checked the [PR](https://github.com/GoogleChromeLabs/ps-analysis-tool/pull/713) and observed a few things were added below.


- [ ] In the CLI, the spacing between strings in the cookie description card is inadequate, affecting readability. 


![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/56af1676-479e-4913-b052-64216dcf3923)

---


- [ ] In the CLI, inside the cookie table data CSV file, the column names are not visible.


![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/b8bae1b2-7b5b-45f3-8834-daf1ea4ed90c)

---

- [ ] The last text is not visible properly when toggling the column names.

![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/26e715ff-0bab-4226-bbcc-e7d12c2b663a)

---

**Comment by amedina** [comment]
@gagan0123 Let's enable the `chrome-launcher` command to receive a `lang=locale` argument.

**Comment by maitreyie-chavan** [comment]
Released in [v0.9](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.9.0)
