### ISSUE TITLE
Epic CLI : Enhancement and issues 

### ISSUE THREAD

**Issue by milindmore22** [GoogleChromeLabs/ps-analysis-tool#623]
The issue will act as EPIC for CLI related enhancement and issues
### CLI :computer:
- [ ] Persistent messaging in CLI, Keep commands history in CLI, so user will be aware which step it breaks also informs user about current progress.
- [ ] Improve overall styling, [possible guide](https://blog.developer.atlassian.com/10-design-principles-for-delightful-clis/)
- [ ] Add validation for command inputs #574 #606
- [ ] Add Error handling for command inputs #606
- [ ] Check Possibility to simulate scroll / click to add user interaction.
- [ ] If CLI runs with no arguments or flags it should show help.
### Reports :chart_with_upwards_trend:
- [ ] Update CLI Dashboard to download reports in HTML.
    - [ ] Add HTML file in zip file along with CSV and JSON files on the CLI dashboard download button.
- [ ] Eliminate Unknown Frames from CLI Dashboard to replicate extension reports.
- [ ] Add CSV download to Cookie issues frame in CLI dashboard.
### Package :package:
- [ ] Publishing cli package via NPM.
- [ ] CLI package to add `--verbose` `--quiet` flags
- [ ] CLI command should only take URL without flag.
- [ ] Add documentation for the CLI package. (Read me inspired by lighthouse)
## Issues :construction:
- [ ] Blocked cookies categories not mapped in CLI dashboard.
- [ ] The Export file of CLI dashboard the columns blocking status, Priority, Size column, but those are missing. We need to add them in table to make consistent with the extension dashboard
