### ISSUE TITLE
CLI Feature Parity

### ISSUE THREAD

**Issue by maitreyie-chavan** [GoogleChromeLabs/ps-analysis-tool#656]
## Feature Request

**Description:**
Unify codebase and feature set with PSAT extension by leveraging the reusable components built
We need to add the following features to the CLI

- [x] Known breakages - PR #708 
- [x] Cookie exemptions - PR #712 
- [x] Blocking direction icons - PR #715

**Comment by ayushnirwal** [comment]
Cookie exemption data will be added by the PR #712

**Comment by maitreyie-chavan** [comment]
Released in [v0.9](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.9.0)
