### ISSUE TITLE
Epic: Display cookies in tabular format

### ISSUE THREAD

**Issue by sayedtaqui** [GoogleChromeLabs/ps-analysis-tool#67]
## Feature Request

**Description:**
List cookies in tabular format with features to sort and filter cookies.

**Acceptance Criteria:**

- [x] https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/68
- [x] https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/69
- [x] https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/70
- [x] https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/71
- [x] https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/72
- [x] https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/7
- [x] https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/73
- [x] https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/66
- [x] https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/99

**Additional Information:**
Some preliminary progress was made in PR https://github.com/GoogleChromeLabs/ps-analysis-tool/pull/56

### Design 
( Needs some improvement )

<img width="1322" alt="image" src="https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/6297436/6e44bcd9-246c-4191-9364-44e50baf9f91">

With Filters

<img width="1332" alt="image" src="https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/6297436/eb73ce4b-5d93-43b6-9355-70d3e6fe769a">

**Comment by sayedtaqui** [comment]
Closing as done
