### ISSUE TITLE
PSAT: Integration with Chrome DevTools Protocol (CDP)

### ISSUE THREAD

**Issue by maitreyie-chavan** [GoogleChromeLabs/ps-analysis-tool#695]
## Feature Request

**Description:**
To maximize the capabilities of the PSAT extension, we need to have an in-depth understanding and integration with Chrome DevTools Protocol (CDP). This Epic aims to comprehensively explore, define and implement ideas by leveraging CDP's features for our extension's functionality.

**Sub-Tasks**

- [x] https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/156
- [x] https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/248
- [x] https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/249
- [x] https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/250
- [x] https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/251
- [x] https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/253
- [x] https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/252
- [x] https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/254
- [x] https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/241
- [x] https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/268
- [x] https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/245
- [x] https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/242
- [x] https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/240
- [x] https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/259
- [x] https://github.com/GoogleChromeLabs/ps-analysis-tool/pull/539

**Comment by maitreyie-chavan** [comment]
Released in [v0.9](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.9.0)
