### ISSUE TITLE
[QA] - Develop branch 

### ISSUE THREAD

**Issue by pavanpatil1** [GoogleChromeLabs/ps-analysis-tool#768]
- [x] [In the extension’s report.html file, the sidebar navigation menu bar scroller on the cookie landing page is not working properly.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/768#issuecomment-2244269485)
- [x] [On the cookie landing page, the Exemption cookie text is not translated, whereas it is translated in the report.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/768#issuecomment-2244290008)
- [x] [ When executing the CLI with the ‘-o’ command the report.html file is not visible in output folder. ](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/768#issuecomment-2244355301)
- [x] [On the page where no cookies are present, the report button is enabled, but the report download button is not working properly. ](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/768#issuecomment-2244389403)
- [x] [The horizontal scroller should appear when multiple filters are selected in the global filter. Also, the menu bar could be positioned a bit lower.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/768#issuecomment-2244742229)
- [x] [Encountering an error during CLI analysis of the Amazon site.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/768#issuecomment-2249373821)
- [x] [The path column sorting filter is not working properly. The column has only one value, but when clicking on the filter, the values are changing.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/768#issuecomment-2249606488)
- [x] [The errors appear when running the build command.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/768#issuecomment-2254406320)
- [x] [WIP] [The httpOnly filter is not working properly. When CDP is off, it works fine, but when enabled, it does not sort properly.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/768#issuecomment-2255086017)
- [x] Extension: [The 'Exempted Cookies' section appears in the report, but it is not visible on the landing page when CDP is turned off, even though it shows up in the report.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/768#issuecomment-2255237394)
- [x] [WIP] [In the report ZIP, the cookies-issue.csv file is missing the 'priority' and 'size' columns. These columns, which are present in the table, are not present in the CSV file.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/768#issuecomment-2255523017)
- [x] [CLI: Report partition key sorting is not working properly.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/768#issuecomment-2255658329)
- [x] [CLI: The downloaded report.html file has a console error.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/768#issuecomment-2255741234)
- [x] [The CSV report downloaded from the cookie table is named as: "-report.csv". To maintain consistency with other reports, could we add the date and time to this report name as well? It should be formatted as "-report.csv](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/768#issuecomment-2249847303)
- [x] @mayan-000  [The horizontal scrollbar is not functioning correctly. Initially, when the devtool is opened, the table columns within the frames are not fully visible, and the horizontal scrollbar does not work.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/768#issuecomment-2255089996)
- [x] [CLI: In the CSV and sitemap execution via CLI, the report.html file is missing the analysis date and time information.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/768#issuecomment-2257892279)
- [x] [The 'Analyze this tab' button is not displayed on one of the tabs immediately after switching from multi-tab to single-tab mode.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/768#issuecomment-2244341597)
- [x] (Known issue) [CLI: GDPR banner not working properly ](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/768#issuecomment-2255649899)

**For Next Release**
- [x] [UI : Extension Reports : The Downloaded Reports display in Light mode when your system and browser preference is dark mode.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/768#issuecomment-2258372075)
- [x] [Extension : We need a proper message to the Blocked cookie section when there are not blocked cookies (ie. count is zero)](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/768#issuecomment-2258106844)
- [x] [Extension: On the cookie landing page, the messages in the "Known Breakages" and "Exempted Cookies" sections are not center-aligned.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/768#issuecomment-2260262251)
- [x] [An unwanted ` symbol is visible after the migration text in the GSI description within the "Known Breakages" section.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/768#issuecomment-2260272297)
- [x] [Extension: In the platform column, if there are entries labeled "Unknown," the sorting functionality does not work correctly. The "Unknown" values are displayed at the top of the list.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/768#issuecomment-2260311061)
- [x] [Extension: The frames section does not work when global filters are applied in the report.
](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/768#issuecomment-2260350081)
- [x] [Extension: In the Exemption Cookie section, the color does not update when selecting an exemption cookie from the filter. The color should change to reflect the selected cookie.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/768#issuecomment-2260412421)
- [x] [CLI: The HttpOnly filter is not functioning correctly on some sites.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/768#issuecomment-2260562185)
- [x] [The "SameSite" column is inconsistently displaying "none" and "None" for empty rows where the SameSite value is absent. It should be consistant to use either "none" or "None" consistently across all entries.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/768#issuecomment-2264468651)
- [x] [CLI : Invalid CSV getting generated when there is JSON value added for cookies.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/768#issuecomment-2260386155)
- [x] [In the Korean translations, some values for the SameSite column appear translated in the table, but after downloading the CSV file, those translations are not visible in the CSV. ](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/768#issuecomment-2264678905)

**Comment by pavanpatil1** [comment]
In the extension’s report.html file, the sidebar navigation menu bar scroller on the cookie landing page is not working properly.

[scroller.webm](https://github.com/user-attachments/assets/3f49d459-1a23-4cb4-bbf2-afaddc9249ad)

**Comment by pavanpatil1** [comment]
On the cookie landing page, the Exemption cookie text is not translated, whereas it is translated in the report.

Landing Page         |  Report
:----------------:|:-------------------------:
<img width="1197" alt="Screenshot 2024-07-23 at 11 02 41 AM" src="https://github.com/user-attachments/assets/f50e8240-87d9-4c6b-af95-33dc4468d9d9">| <img width="1227" alt="Screenshot 2024-07-23 at 11 03 59 AM" src="https://github.com/user-attachments/assets/21011b19-b804-4e38-908c-da3009afc010">

**Comment by pavanpatil1** [comment]
The 'Analyze this tab' button is not displayed on one of the tabs immediately after switching from multi-tab to single-tab mode.

**Steps to reproduce:** 
1. Enable multi-tab processing and analyze 3-4 tabs.
2. Disable the multi-tab settings and review all tabs. You should notice that cookies are still visible in tab where we close the mutitab settings. 
3. Reopen the DevTools on that tab and observe the results.


[multitab.webm](https://github.com/user-attachments/assets/84cf7566-0bfa-48d0-bad0-05217ddf4383)

**Comment by pavanpatil1** [comment]
When executing the CLI with the ‘-o’ parameter the report.html file is not visible in output folder. 


<img width="742" alt="Screenshot 2024-07-23 at 11 59 19 AM" src="https://github.com/user-attachments/assets/bab87f62-506b-4145-a5ed-1d3bc4bca5fd">

**Comment by pavanpatil1** [comment]
On the page where no cookies are present, the report button is enabled, but the report download button is not working properly. 

[example.webm](https://github.com/user-attachments/assets/a3c9e7c7-da2c-496f-8abb-bef68e89cd4e)

**Comment by pavanpatil1** [comment]
The horizontal scroller should appear when multiple filters are selected in the global filter. Also, the menu bar could be positioned a bit lower.

<img width="1455" alt="Screenshot 2024-07-23 at 3 08 26 PM" src="https://github.com/user-attachments/assets/0c968cad-4d72-47b7-bb5a-5e887d7bcb8a">

**Comment by pavanpatil1** [comment]
Encountering an error during CLI analysis of the Amazon site.


<img width="1448" alt="Screenshot 2024-07-25 at 10 03 36 AM" src="https://github.com/user-attachments/assets/a8643860-152c-4ddd-a83f-10a90a52f449">

**Comment by pavanpatil1** [comment]
The path column sorting filter is not working properly.  The column has only one value, but when clicking on the filter, the values are changing.

[path.webm](https://github.com/user-attachments/assets/401bf6c7-804f-434c-a327-30fd8067805d)

**Comment by pavanpatil1** [comment]
The CSV report downloaded from the cookie table is named as: "<site-name>-report.csv". To maintain consistency with other reports, could we add the date and time to this report name as well? It should be formatted as "<site-name>-report<date-time>.csv


<img width="1455" alt="Screenshot 2024-07-25 at 2 37 47 PM" src="https://github.com/user-attachments/assets/9a72ebd4-8987-474f-b4f9-5a8d160c2b6e">

**Comment by pavanpatil1** [comment]
The errors appear when running the build command.

<img width="1453" alt="Screenshot 2024-07-28 at 2 36 07 PM" src="https://github.com/user-attachments/assets/180f81d4-02ff-4703-becc-6f84a32d032c">

**Comment by pavanpatil1** [comment]
The httpOnly filter is not working properly. When CDP is off, it works fine, but when enabled, it does not sort properly.


[http.webm](https://github.com/user-attachments/assets/838cb0d6-5408-4b8a-86e0-89a2e44ab045)

**Comment by pavanpatil1** [comment]
The horizontal scrollbar is not functioning correctly. Initially, when the devtool is opened, the table columns within the frames are not fully visible, and the horizontal scrollbar does not work.

[scroll.webm](https://github.com/user-attachments/assets/1ecb70c4-a7a2-4cf3-aabc-8897e8f79887)

**Comment by pavanpatil1** [comment]
The 'Exempted Cookies' section appears in the report, but it is not visible on the landing page when CDP is turned off, even though it shows up in the report


<img width="1461" alt="Screenshot 2024-07-29 at 1 15 31 PM" src="https://github.com/user-attachments/assets/680c4fee-8fae-4d70-82e1-3b5d4f796825">

**Comment by pavanpatil1** [comment]
In the report ZIP, the cookies-issue.csv file is missing the 'priority' and 'size' columns. These columns, which are present in the table, are not present in the CSV file.

<img width="999" alt="Screenshot 2024-07-29 at 3 34 28 PM" src="https://github.com/user-attachments/assets/ae4775bd-6f6e-4506-a541-32b3f3da900e">

**Comment by pavanpatil1** [comment]
On the NYTimes site, in the cookie.csv file, For the cookie '_v__cb_cp' the priority column is not correctly displayed; it appears within the size column instead.


<img width="1181" alt="Screenshot 2024-07-29 at 3 54 34 PM" src="https://github.com/user-attachments/assets/72409ba7-4e1a-43e9-8a64-280e13457627">

**Comment by pavanpatil1** [comment]
In the report.html file, sorting of the 'SameSite' column is not functioning properly.

[samesite.webm](https://github.com/user-attachments/assets/8f18ec7b-492c-43de-bed4-584a868a5ec4)

**Comment by milindmore22** [comment]
CLI : Ignore GDPR `-i` CLI option is not working correctly in both cases. It shows the same number of cookies on both accepted and ignored cases.

Tested on 
1) https://aljazeera.com/ 
2) https://www.singaporeair.com/

Default (Accepted GDPR banner) **Cookie Count: 64**
![image](https://github.com/user-attachments/assets/cb73adec-0d07-4fb0-95f9-d494bfb06e0d)

Ignore blank (Ignore GDPR banner) **Cookie Count : 64**

![image](https://github.com/user-attachments/assets/eb85a033-1d5f-4d52-97d9-e9c9f1066dd2)

**Comment by milindmore22** [comment]
CLI: Partition key column from CLI report sorting is not working properly.

https://github.com/user-attachments/assets/7515ed85-f370-46d4-be33-4a5269727f2a

**Comment by milindmore22** [comment]
CLI: The downloaded report.html file has a console error.

`GET file:///Users/milind/Downloads/psat_cli_report_aljazeera-com_2024-07-29_17-21-52/index.js net::ERR_FILE_NOT_FOUND`

![image](https://github.com/user-attachments/assets/20f25c29-9b72-45da-858e-a94f31200fb8)

**Comment by milindmore22** [comment]
Extension : We need a proper message to the Blocked cookie section when there are not blocked cookies (ie. count is zero)
![image](https://github.com/user-attachments/assets/8da1ff92-2fad-4c52-8af7-8396878bbe57)

You can visit example site homepage https://domain-aaa.com/

**Comment by milindmore22** [comment]
Extension Reports : The Downloaded Reports display in Light mode when your system and browser preference is dark mode.
![image](https://github.com/user-attachments/assets/404b3ba4-0621-4f1e-bc1b-f2c84bc79cf9)

**Comment by pavanpatil1** [comment]
Extension: On the cookie landing page, the messages in the "Known Breakages" and "Exempted Cookies" sections are not center-aligned.

<img width="1087" alt="स्क्रीनशॉट 2024-07-31, अ 4 36 00 पर" src="https://github.com/user-attachments/assets/3d97fc80-a1a5-4994-8c84-1f83af1f6883">

**Comment by pavanpatil1** [comment]
An unwanted ` symbol is visible after the migration text in the GSI description within the "Known Breakages" section.


<img width="1222" alt="Screenshot 2024-07-31 at 4 09 56 PM" src="https://github.com/user-attachments/assets/17c80dd8-2da8-49c3-8337-266af8ec5406">

**Comment by pavanpatil1** [comment]
Extension: In the platform column, if there are entries labeled "Unknown," the sorting functionality does not work correctly. The "Unknown" values are displayed at the top of the list. 


[platform.webm](https://github.com/user-attachments/assets/e9bed3a6-52b5-468f-b781-6186c1a4d2d0)

**Comment by pavanpatil1** [comment]
Extension: The frames section does not work when global filters are applied in the report.

[frames.webm](https://github.com/user-attachments/assets/e1b70d30-e27c-4a3a-9c5d-0382d772c28e)

**Comment by milindmore22** [comment]
CLI : Invalid CSV getting generated when there is JSON value added for cookies.

Steps to reproduce. 
1. psat -u https://spectator.org/defund-npr-yesterday/
2. It will generate a report, open it.
3. Click Download from Cookie landing page.
4. extract zip file
5. Open `cookies.csv`
6. Look for `plsGeoObj` with value in JSON format `{"ip":"117.202.207.242","country":"IN","region":"MH","city":"Pune","zip":"411004","location":"18.6161,73.7286"}`

The value is not parsing correctly due to double quotes, creating invalid CSV

https://csvlint.io/validation/66aa2855b7d0ed000200006b

**Comment by pavanpatil1** [comment]
CLI: The HttpOnly filter is not functioning correctly on some sites.


[httponly.webm](https://github.com/user-attachments/assets/6189d6f7-27c1-4b6a-9d25-952c5a68e606)

**Comment by pavanpatil1** [comment]
The "SameSite" column is inconsistently displaying "none" and "None" for empty rows where the SameSite value is absent. It should be consistant to use either "none" or "None" consistently across all entries.

<img width="979" alt="Screenshot 2024-08-02 at 9 04 06 AM" src="https://github.com/user-attachments/assets/17c1cf55-b585-4b48-b851-fdcc014b5b65">

**Comment by pavanpatil1** [comment]
In the Korean translations, some values for the `SameSite` column appear translated in the table, but after downloading the CSV file, those translations are not visible in the CSV.

<img width="1464" alt="Screenshot 2024-08-02 at 12 11 06 PM" src="https://github.com/user-attachments/assets/4fd0146c-1bce-42a4-8e4a-51fbca04fa0a">

**Comment by pavanpatil1** [comment]
Fixed and Released as a part of [v0.10](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.10.0)
