### ISSUE TITLE
Wiki updates for PSAT v0.11

### ISSUE THREAD

**Issue by milindmore22** [GoogleChromeLabs/ps-analysis-tool#826]
- [x] [#780](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/780) Feature separation and Feature navigation widget for each PSAT section
   - [x] PR: [#808](https://github.com/GoogleChromeLabs/ps-analysis-tool/pull/808)
   - [x] Wiki Page: [Related Website Set](https://github.com/GoogleChromeLabs/ps-analysis-tool/wiki/Related-Website-Sets)
   - [x] Screenshots: All screenshots on [Related Website Set](https://github.com/GoogleChromeLabs/ps-analysis-tool/wiki/Related-Website-Sets) page showcasing tabs.
- [x] [#799](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/799) Redesign PSAT Landing page
   - [x] PR: 
   - [x] Wiki Page: [PSAT Landing page](https://github.com/GoogleChromeLabs/ps-analysis-tool/wiki/PSAT-Landing-Page) 
   - [ ] Screenshots :
- [x] [#809](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/809) Support for Aggregated CSV format for downloaded PSAT CLI Report
   - [x] PR:[#814](https://github.com/GoogleChromeLabs/ps-analysis-tool/pull/814)
   - [x] Wiki Page:  [PSAT Command Line Interface](https://github.com/GoogleChromeLabs/ps-analysis-tool/wiki/PSAT-Command-Line-Interface#gdpr) Output Section.
   - [ ] Screenshots :
- [x] [#810](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/810) Expanded support for GDPR banner acceptance feature
   - [x] PR:[#823](https://github.com/GoogleChromeLabs/ps-analysis-tool/pull/823)
   - [x] Wiki Page: [PSAT Command Line Interface](https://github.com/GoogleChromeLabs/ps-analysis-tool/wiki/PSAT-Command-Line-Interface#gdpr) GDPR section
   - [ ] Screenshots :
- [x] [#815](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/815) PSAT CLI: Version Check and Update Prompt for PSAT CLI
  - [x] PR: [#822](https://github.com/GoogleChromeLabs/ps-analysis-tool/pull/822)
  - [x] Wiki Page: [PSAT Command Line Interface](https://github.com/GoogleChromeLabs/ps-analysis-tool/wiki/PSAT-Command-Line-Interface)
  - [ ] Screenshots: 
- [x] [#820](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/820) - Add Wiki section in extension.
   - [x] PR:[#816](https://github.com/GoogleChromeLabs/ps-analysis-tool/pull/816)
   - [x] Wiki Page: [PSAT Landing page](https://github.com/GoogleChromeLabs/ps-analysis-tool/wiki/PSAT-Landing-Page)
   - [ ] Screenshots: Update screenshots on [PSAT Landing page](https://github.com/GoogleChromeLabs/ps-analysis-tool/wiki/PSAT-Landing-Page)
- [x] [#807](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/807) - Review output messages on the PSAT CLI
   - [x] PR: [#806](https://github.com/GoogleChromeLabs/ps-analysis-tool/pull/806)  
   - [x] Wiki Page: [PSAT Command Line Interface](https://github.com/GoogleChromeLabs/ps-analysis-tool/wiki/PSAT-Command-Line-Interface)
   - [ ] Screenshots: Update [PSAT Command Line Interface](https://github.com/GoogleChromeLabs/ps-analysis-tool/wiki/PSAT-Command-Line-Interface) for command line screenshot use `-v` also update CLI dashboard showing version in the top-right corner
 - [x] Deprecate wappalayzer as it's no longer provides robust results.
    - [x] PR #833 
    - [x] Wiki Page : [PSAT Command Line Interface](https://github.com/GoogleChromeLabs/ps-analysis-tool/wiki/PSAT-Command-Line-Interface)
    - [ ] screesnots :

**Comment by gagan0123** [comment]
Released as a part of [v0.11.0](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.11.0)
