### ISSUE TITLE
[Epic] Stories in PSAT 

### ISSUE THREAD

**Issue by maitreyie-chavan** [GoogleChromeLabs/ps-analysis-tool#897]
## Feature Request

**Description:**
As part of the Explorable Explanations, include content in Story format, leveraging Google's Web Stories open source library. Web Stories are a web-based version of the popular “Stories” format that blend video, audio, images, animation, and text to create a dynamic consumption experience. Stories in PSAT let users explore content in a modern format and at their own pace by tapping through it, or swiping from one piece of content to the next. 

**WIP Design Mock up:**

<img width="1065" alt="image (27)" src="https://github.com/user-attachments/assets/5d016017-26b0-408f-bf42-f12d133d3247" />

---

**Acceptance Criteria**
- [x] The UI of the stories should match the mock-up.
- [x] The stories should be dynamically fetched from the server.
- [x] The stories filters should be dynamically fetched from the server.
- [x] The user should be able to filter stories according to the filters displayed in the UI.
- [x] There should be an infinite scrolling mechanism for the stories to load.
- [x] The search feature should work (i.e. the text that is entered should be searched within the story title, excerpt and content).
- [x] The user should have the ability to sort the stories from `Newest` to `Oldest`.

**Comment by maitreyie-chavan** [comment]
Released in [v0.13.0](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.13.0) 🚀
